### ISSUE TITLE
2d图轴体没有两只耳朵的洞，3d图里有

### ISSUE THREAD

**Issue by milesking** [xulu199705/KeyBoard87#2]
首先多谢分享项目，正在学习ad20, 尝试自己修改打板。有个疑问，为啥2d图没有轴体耳朵的洞，3d图有。打板出来有那两个孔吗？多谢！

**Comment by xulu199705** [comment]
> 首先多谢分享项目，正在学习ad20, 尝试自己修改打板。有个疑问，为啥2d图没有轴体耳朵的洞，3d图有。打板出来有那两个孔吗？多谢！

https://github.com/xulu199705/KeyBoard87/blob/master/Reference/Cherry_MX/Cherry_MX_sw.pdf
这是cherry mx轴的参考文档，重点看第2页下方的图。
mx轴有分为有/无固定引脚的样式，为了配合我手头的轴，我用的是没有固定引脚的轴的PCB封装；
如果你需要做有固定引脚的轴的封装，可能需要到元器件库去修改一下（我不确定有没有现成的）；
另外，3D的模型是我从网上down下来的，主要是为了好（zhuang）看（bi），所以会有点偏差，rgb那两个引脚也是不一样的。

**Comment by milesking** [comment]
好的，多谢
